export const CODES = {
  DEFAULT_ERROR_CODE: 500,
  DEFAULT_SUCCESS_CODE: 200,
  UNAUTHORIZED_CODE: 401,
  BAD_REQUEST_CODE: 400,
  NOT_FOUND_CODE: 404,
  INTERNAL_SERVER_ERROR: 500,
  UNSUPPORTED_MEDIA_TYPE: 415,
};
